yaml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-11-jdk -y

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code
        run: scp -r ./springboot-backend/* ec2-user@${{ secrets.SERVER_IP_ADDRESS }}:/home/ec2-user/app

      - name: Restart server
        run: ssh ec2-user@${{ secrets.SERVER_IP_ADDRESS }} "sudo systemctl restart springboot-backend"