# Deploy script for frontend and backend Docker containers on AWS Elastic Beanstalk
# This script assumes that you have already set up your AWS credentials and Elastic Beanstalk environment

on:
  push:
    branches:
      - main # replace with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade

      - name: Deploy react-frontend app
        run: |
          cd react-frontend
          eb init CapstoneProject-env --platform docker --region us-east-1
          eb deploy

      - name: Deploy springboot-backend app
        run: |
          cd springboot-backend
          eb init CapstoneProject-env --platform docker --region us-east-1
          eb deploy

# name: Deployment
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up JDK 20
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           # distribution: 'adopt'
#           java-version: 20
#       - name: Build with Maven
#         run: mvn -B package -DskipTests --file springboot-backend/pom.xml
#       - name: Upload JAR
#         uses: actions/upload-artifact@v3
#         with:
#           name: artifact
#           path: springboot-backend/target/capstone-0.0.1-SNAPSHOT.jar
#   deploy:
#     needs: build
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Download JAR
#         uses: actions/download-artifact@v3
#         with:
#           name: artifact
#       #Deploy the artifact (JAR) into AWS Beanstalk
#       - name: Deploy to EB
#         uses: einaregilsson/beanstalk-deploy@v15
#         with:
#           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           application_name: longdh21part2
#           environment_name: Longdh21part2-env
#           version_label: ${{github.SHA}}
#           region: us-east-1
#           deployment_package: capstone-0.0.1-SNAPSHOT.jar
#           use_existing_version_if_available: true