name: Build and deploy JAR app to Azure Web App - nihongolevelup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Change to the springboot-backend directory
        run: cd springboot-backend

      - name: Build with Maven
        run: mvn -f /home/runner/work/Capstone/Capstone/springboot-backend/pom.xml clean install -Dmaven.test.skip=true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nihongolevelup'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7EAAE3A1DD95432E843B97CEA25E77C2 }}
          package: '*.jar'
